# Generated by Django 5.2.12 on 2026-03-28 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('review', 'review'), ('blog', 'blog')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('person_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('body', models.TextField()),
                ('turnstile_meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
