# Generated by Django 5.2.12 on 2026-03-30 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': '問い合わせ', 'verbose_name_plural': '問い合わせ'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.TextField(verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='person_name',
            field=models.CharField(max_length=100, verbose_name='担当者名'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject_type',
            field=models.CharField(choices=[('review', 'レビュー依頼'), ('blog', 'ブログ関連')], max_length=20, verbose_name='問い合わせ種別'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='turnstile_meta',
            field=models.JSONField(blank=True, null=True, verbose_name='Turnstile検証情報'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
