# Generated by Django 5.2.12 on 2026-03-31 11:16

import django.db.models.deletion
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='コード')),
                ('label', models.CharField(max_length=100, verbose_name='表示名')),
                ('default_text', models.TextField(blank=True, null=True, verbose_name='既定文言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'オプション',
                'verbose_name_plural': 'オプション',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='タグ名')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, verbose_name='slug')),
                ('summary', models.CharField(max_length=200, verbose_name='要約')),
                ('body_html', models.TextField(verbose_name='本文HTML')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('publish', '公開'), ('private', '非公開')], default='draft', max_length=20, verbose_name='公開状態')),
                ('twitter_card', models.CharField(choices=[('summary', 'summary'), ('summary_large_image', 'summary_large_image')], default='summary_large_image', max_length=30, verbose_name='Twitter Card種別')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('views_total', models.PositiveBigIntegerField(default=0, verbose_name='累計PV')),
                ('toc_json', models.JSONField(blank=True, default=list, verbose_name='目次JSON')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='ロック取得日時')),
                ('lock_token', models.UUIDField(blank=True, null=True, verbose_name='ロックトークン')),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ロック有効期限')),
                ('image_job_status', models.CharField(choices=[('pending', '処理待ち'), ('processing', '処理中'), ('completed', '完了'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='画像処理状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='執筆者')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_articles', to=settings.AUTH_USER_MODEL, verbose_name='ロック中ユーザー')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePublishRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='状態')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='対応日時')),
                ('note', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_requests', to='cms.article', verbose_name='記事')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_article_publish_requests', to=settings.AUTH_USER_MODEL, verbose_name='対応者')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_publish_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
            options={
                'verbose_name': '公開申請',
                'verbose_name_plural': '公開申請',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSaveLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='発生日時')),
                ('lock_token', models.UUIDField(verbose_name='ロックトークン')),
                ('target', models.CharField(blank=True, max_length=255, null=True, verbose_name='対象')),
                ('status', models.CharField(choices=[('failed', '失敗'), ('started', '開始'), ('completed', '完了')], max_length=20, verbose_name='状態')),
                ('message', models.TextField(blank=True, null=True, verbose_name='メッセージ')),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_save_logs', to=settings.AUTH_USER_MODEL, verbose_name='実行ユーザー')),
            ],
            options={
                'verbose_name': '記事保存ログ',
                'verbose_name_plural': '記事保存ログ',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='slug')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='cms.category', verbose_name='親カテゴリ')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='cms.category', verbose_name='カテゴリ'),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, unique=True, verbose_name='ファイル名')),
                ('width', models.PositiveIntegerField(default=1, verbose_name='横幅')),
                ('height', models.PositiveIntegerField(default=1, verbose_name='高さ')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA256')),
                ('exif_json', models.JSONField(blank=True, null=True, verbose_name='EXIF')),
                ('processing_options_json', models.JSONField(blank=True, null=True, verbose_name='処理オプション')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='cms.article', verbose_name='記事')),
            ],
            options={
                'verbose_name': 'メディアアセット',
                'verbose_name_plural': 'メディアアセット',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cms.mediaasset', verbose_name='サムネイルアセット'),
        ),
        migrations.CreateModel(
            name='ArticleOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('override_text', models.TextField(blank=True, null=True, verbose_name='上書き文言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_options', to='cms.article', verbose_name='記事')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_options', to='cms.option', verbose_name='オプション')),
            ],
            options={
                'verbose_name': '記事オプション',
                'verbose_name_plural': '記事オプション',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='options',
            field=models.ManyToManyField(related_name='articles', through='cms.ArticleOption', to='cms.option', verbose_name='記事オプション'),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='cms.article', verbose_name='記事')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='cms.tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '記事タグ',
                'verbose_name_plural': '記事タグ',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='cms.ArticleTag', to='cms.tag', verbose_name='タグ'),
        ),
        migrations.CreateModel(
            name='ArticleOgpInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(verbose_name='URL')),
                ('title', models.TextField(blank=True, null=True, verbose_name='タイトル')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='概要')),
                ('thumbnail', models.TextField(blank=True, null=True, verbose_name='サムネイルURL')),
                ('site_name', models.TextField(blank=True, null=True, verbose_name='サイト名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogp_infos', to='cms.article', verbose_name='記事')),
            ],
            options={
                'verbose_name': '記事OGPキャッシュ',
                'verbose_name_plural': '記事OGPキャッシュ',
                'ordering': ['url'],
                'constraints': [models.UniqueConstraint(fields=('article', 'url'), name='cms_article_ogp_info_article_url_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='articleoption',
            constraint=models.UniqueConstraint(fields=('article', 'option'), name='cms_article_option_unique'),
        ),
        migrations.AddConstraint(
            model_name='articletag',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='cms_article_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='cms_article_category_slug_unique'),
        ),
    ]
