# Generated by Django 5.2.12 on 2026-04-08 07:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_articlesavelog_article'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articletag',
            index=models.Index(fields=['tag', 'article'], name='cms_arttag_tag_article_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='cms_tag_lower_name_idx'),
        ),
    ]
