# Generated by Django 5.2.12 on 2026-04-08 08:44

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_articletag_cms_arttag_tag_article_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleoption',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='article',
            name='options',
        ),
        migrations.RemoveField(
            model_name='option',
            name='default_text',
        ),
        migrations.AddField(
            model_name='article',
            name='option',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None, verbose_name='記事オプションID'),
        ),
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明文'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['option'], name='cms_article_option_gin'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), name='cms_option_label_ci_unique'),
        ),
        migrations.DeleteModel(
            name='ArticleOption',
        ),
    ]
