# Generated by Django 5.2.12 on 2026-04-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_repair_option_description_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='original_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='オリジナルファイルパス'),
        ),
    ]
