# Generated by Django 5.2.12 on 2026-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_mediaasset_original_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='original_file_path',
            field=models.CharField(max_length=500, verbose_name='オリジナルファイルパス'),
        ),
    ]
