# Generated by Django 5.2.12 on 2026-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_mediaasset_original_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_profit',
            field=models.BooleanField(default=True, verbose_name='収益化'),
        ),
    ]
