# Generated by Django 5.2.12 on 2026-04-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_article_is_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleogpinfo',
            name='is_associates',
            field=models.BooleanField(blank=True, null=True, verbose_name='アソシエイト'),
        ),
        migrations.AddField(
            model_name='articleogpinfo',
            name='price',
            field=models.TextField(blank=True, null=True, verbose_name='価格'),
        ),
    ]
