apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DJANGO_SETTINGS_MODULE: "syumatsucamera.settings.production"
  DEBUG: "False"
  ALLOWED_HOSTS: "syumatsucamera.com,cms.syumatsucamera.com"
  DJANGO_CSRF_TRUSTED_ORIGINS: "https://syumatsucamera.com,https://cms.syumatsucamera.com"
  POSTGRES_DB: "syumatsucamera"
  POSTGRES_USER: "app_prod_user"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_URL: "redis://redis:6379/0"
  REDIS_CONNECT_TIMEOUT: "3"
  REDIS_SOCKET_TIMEOUT: "3"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  LOG_DIR: "/var/log/syumatsucamera"
  LOG_RETENTION_DAYS: "30"
  APP_LOG_LEVEL: "INFO"
  LOG_FILE_INFO: "info.log"
  LOG_FILE_CRITICAL: "critical.log"
  CDN_BASE_URL: "https://media.syumatsucamera.com/"
