# Generated by Django 5.2.12 on 2026-03-28 16:09

import django.db.models.functions.text
import users.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cf_access_sub', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.CharField(blank=True, max_length=300, null=True)),
                ('icon', models.CharField(blank=True, max_length=500, null=True)),
                ('header_image', models.CharField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('author', 'author')], default='author', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['email'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_user_email_lower_unique'), models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'author'])), name='users_user_role_valid'), models.CheckConstraint(condition=models.Q(('is_active', False), models.Q(('cf_access_sub__isnull', False), models.Q(('cf_access_sub', ''), _negated=True), ('display_name__isnull', False), models.Q(('display_name', ''), _negated=True), ('profile__isnull', False), models.Q(('profile', ''), _negated=True), ('icon__isnull', False), models.Q(('icon', ''), _negated=True), ('header_image__isnull', False), models.Q(('header_image', ''), _negated=True)), _connector='OR'), name='users_user_active_requires_registration_fields')],
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
