# Generated by Django 5.2.12 on 2026-03-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_cf_access_sub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが任意に追加するキー/値のメタ情報を保持する。', verbose_name='任意メタ情報'),
        ),
    ]
