# Generated by Django 5.2.12 on 2026-04-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='WebサイトURL'),
        ),
        migrations.AddField(
            model_name='user',
            name='x_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='X URL'),
        ),
    ]
